const black = "<p>Behold, the yarn of the deepest black, woven with strands of midnight and mystery. It exudes power, evoking both fear and reverence. This is a yarn for those who seek to make a statement, to stand out from the crowd, and to command respect. With every stitch, the knitter imbues their creation with the darkness that lies within all of us, a reminder of our mortality and the infinite possibilities that come with it. Let this yarn be your tool for transformation, a reminder that even in the darkest moments, there is beauty to be found.</p>";
const gray = "<p>Behold, the enchanted yarn of gray, a color that embodies neutrality and balance. This yarn has been imbued with the power to soothe and calm, to help us find a sense of peace amidst the chaos of our daily lives. It is the perfect yarn for creating cozy blankets and comforting accessories that will wrap us up in a warm embrace. With this yarn, we can create something that not only looks beautiful, but also brings a sense of calm and serenity into our homes. So let us embrace the enchantment of gray, and create something truly magical together.</p>";
const white = "<p>White, the color of purity and innocence, is an enchanting hue in the world of yarn. Imagine a skein of white yarn, as soft as freshly fallen snow, that has the power to soothe and calm the mind. As you knit or crochet with this yarn, you feel a sense of clarity and simplicity wash over you. It's as if the yarn has the ability to clear away any distractions and help you focus on the task at hand. The finished product is a beautiful, ethereal creation that embodies the purity and serenity of the color white.</p>";
const purple = "<p>Ah, purple, the color of royalty and power. But it's also the color of spirituality, creativity, and magic. And this enchanting yarn in shades of violet and lavender embodies all of those qualities. Knitting with this yarn will transport you to a mystical realm where anything is possible. Its soft, luxurious fibers will caress your fingers as you create something truly enchanting. Let the color purple inspire you to tap into your inner wisdom and creativity, and let this yarn be your guide on a journey of self-discovery and magic.</p>";
const blue = "<p>In the world of yarn, there's no shade quite like blue. It speaks to the depth of the ocean and the vastness of the sky, evoking feelings of calm, serenity, and peace. Imagine a skein of yarn that captures the very essence of these emotions, with every stitch conjuring the tranquility of a quiet sea and the limitless expanse of a clear sky. A scarf knit from this yarn could wrap the wearer in a comforting embrace, offering a respite from the chaos of daily life. With each stitch, the calming influence of this blue yarn can help to soothe the soul and quiet the mind, creating a truly magical and therapeutic knitting experience.</p>";
const green = "<p>Behold the magical Green Enchantment yarn, imbued with the power to inspire growth, renewal, and harmony. Each stitch with this yarn will bring a sense of balance to the mind and soul, reminding us to connect with nature and find serenity in our surroundings. Let its lush green color evoke feelings of new beginnings and the energy of the earth, making every project a symbol of personal growth and transformation. Let Green Enchantment take you on a journey of tranquility and peace.</p>";
const red = "<p>Behold, the fiery red yarn before you, pulsing with the intensity of passion and desire. This enchanted fiber ignites the flames of emotion within you, daring you to embrace the thrill of the moment. Red is the color of power, of love, and of unbridled energy. With each stitch, you infuse this yarn with your own fiery spirit, channeling its power into your creation. So let the boldness of red fuel your imagination, and let your knitting blaze with the heat of your own unstoppable spirit.</p>";
const orange = "<p>Behold the enchanted orange yarn, a wondrous creation that brings with it the power of enthusiasm and warmth. This yarn is not just a color, it is a feeling - one that fills your heart with excitement and joy. Just like the sun rising over a new day, this yarn will infuse your life with the energy to tackle anything that comes your way. Whether you're feeling down or need an extra boost, this yarn is the perfect companion to lift your spirits and light up your world. So grab your needles, immerse yourself in the glorious orange hue, and let the magic of this yarn envelope you in a warm, comforting embrace.</p>";
const yellow = "<p>Imagine a stunning yarn that glimmers with the brilliant light of yellow, a color that evokes happiness, optimism, and warmth. When you hold it, you can almost feel the sun on your skin and the joy of a perfect summer day. This enchanted yarn holds within it the power to lift spirits and brighten moods. With each stitch, the yarn seems to radiate a golden aura, reminding us that even in the darkest of times, there is always a glimmer of hope and sunshine to be found. So let this yarn be a beacon of light in your life, and allow it to infuse your creations with the warm glow of positivity.</p>";

const wool = "<p>Wool yarn, with its rustic texture and natural hues, is a fiber steeped in history and tradition. It exudes warmth and coziness, and has the power to transport you to a simpler time when life was lived at a slower pace. Each skein is a testament to the beauty of the natural world, where sheep roam freely and their wool is lovingly sheared by skilled hands. When you work with wool, you can feel the connection to the earth and to the animals that provide us with this precious resource. So embrace the magic of wool yarn, and let it weave a story of comfort and nostalgia into every stitch.</p>";
const cotton = "<p>Cotton yarn is the epitome of softness and versatility. It's a classic fiber that has been used for centuries, and for good reason. The natural breathability of cotton makes it ideal for warm-weather garments and accessories. But it's not just a one-season wonder; cotton can also be used to create cozy and comfortable pieces for cooler weather. Its smooth, silky texture feels delightful against the skin, and its ability to absorb moisture makes it perfect for items like dishcloths and washcloths. Whether you're a fan of bright colors or neutral tones, cotton yarn comes in a wide variety of shades, ensuring that you can find the perfect color for your project. So why not give this versatile fiber a try and see what kind of magic you can create?</p>";
const alpaca = "<p>Ah, alpaca yarn, a true marvel of nature. So soft and warm, with a gentle drape and a subtle sheen. Alpaca fibers have been prized for centuries for their luxurious feel and excellent insulation. This yarn will hug you in its warmth like a soft embrace, and the natural hues will remind you of the earth and its raw beauty. Whether you're making a cozy sweater or a delicate shawl, alpaca yarn is a perfect choice for those who appreciate the finer things in life.</p>";

const fingering = "<p>Fingering weight yarn, with its delicate strands and fine texture, is like the whisper of a secret. It's the kind of yarn that requires patience and attention to detail, but rewards you with a finished product that is both light and airy, yet strong and resilient. With fingering weight yarn, you have the power to create intricate lace shawls, cozy socks, and delicate accessories that will last a lifetime. It may seem small and insignificant at first glance, but make no mistake, fingering weight yarn is a force to be reckoned with in the world of fiber arts.</p>";
const sport = "<p>Sport weight yarn is a magical and elusive creature in the world of fiber arts. It embodies a delicate balance of strength and softness, making it the perfect companion for any creative endeavor. It has the power to transform the mundane into something extraordinary, adding a touch of enchantment to your projects. Its ethereal nature is both alluring and elusive, calling to you with a siren song that only the most experienced crafters can resist. Once you have tamed this elusive creature, however, its true beauty will be revealed, and you will be rewarded with creations that are both elegant and otherworldly.</p>";
const dk = "<p>Ah, DK weight yarn, a truly mystical fiber. Its weight and texture are the perfect medium for casting spells with your knitting needles. With its mysterious ability to take on the qualities of any fiber it's spun from, DK weight yarn can transform a mundane pattern into a work of art. Its pliability allows for intricate stitch work, while its substantial weight provides structure and warmth to any garment. The possibilities are endless when you allow yourself to be enchanted by the magic of DK weight yarn.</p>";
const worsted = "<p>In the hands of a skilled artisan, worsted weight yarn is a force to be reckoned with. Its strong and sturdy fibers form a foundation upon which dreams are built. With each stitch, it weaves a tale of warmth and comfort, a story of coziness and familiarity. Its weight and substance provide the perfect balance between softness and structure, making it the ideal choice for any project where durability and drape are paramount. It is a yarn that is both timeless and modern, classic and innovative, and with every skein, the possibilities are endless.</p>";

const products = [
    {"id": 1, "manufacturer": "Malabrigo", "model": "Mechita", "price": 20.00, "weight": "Fingering", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "fingering", "black"], "color": "Black", "description": black+wool+fingering, "image": "/images/yarn/black.avif"},
    {"id": 2, "manufacturer": "Malabrigo", "model": "Mechita", "price": 20.00, "weight": "Fingering", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "fingering", "gray"], "color": "Gris", "description": gray+wool+fingering, "image": "/images/yarn/gray.avif"},
    {"id": 3, "manufacturer": "Malabrigo", "model": "Mechita", "price": 20.00, "weight": "Fingering", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "fingering", "purple"], "color": "Sabiduria", "description": purple+wool+fingering, "image": "/images/yarn/purple.avif"},
    {"id": 4, "manufacturer": "Malabrigo", "model": "Mechita", "price": 20.00, "weight": "Fingering", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "fingering", "blue"], "color": "Azul Profundo", "description": blue+wool+fingering, "image": "/images/yarn/blue.avif"},
    {"id": 5, "manufacturer": "Malabrigo", "model": "Mechita", "price": 20.00, "weight": "Fingering", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "fingering", "green"], "color": "Fiona", "description": green+wool+fingering, "image": "/images/yarn/green.avif"},
    {"id": 6, "manufacturer": "Malabrigo", "model": "Mechita", "price": 20.00, "weight": "Fingering", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "fingering", "yellow"], "color": "Frank Ochre", "description": yellow+wool+fingering, "image": "/images/yarn/yellow.avif"},
    {"id": 7, "manufacturer": "Malabrigo", "model": "Mechita", "price": 20.00, "weight": "Fingering", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "fingering", "orange"], "color": "Sunset", "description": orange+wool+fingering, "image": "/images/yarn/orange.avif"},
    {"id": 8, "manufacturer": "Malabrigo", "model": "Mechita", "price": 20.00, "weight": "Fingering", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "fingering", "red"], "color": "Ravelry Red", "description": red+wool+fingering, "image": "/images/yarn/red.avif"},
    {"id": 9, "manufacturer": "Malabrigo", "model": "Mechita", "price": 20.00, "weight": "Fingering", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "fingering", "white"], "color": "Whole Grain", "description": white+wool+fingering, "image": "/images/yarn/white.avif"},
    
    {"id": 11, "manufacturer": "Malabrigo", "model": "Arroyo", "price": 20.00, "weight": "Sport", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "sport", "black"], "color": "Black", "description": black+wool+sport, "image": "/images/yarn/black.avif"},
    {"id": 12, "manufacturer": "Malabrigo", "model": "Arroyo", "price": 20.00, "weight": "Sport", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "sport", "gray"], "color": "Gris", "description": gray+wool+sport, "image": "/images/yarn/gray.avif"},
    {"id": 13, "manufacturer": "Malabrigo", "model": "Arroyo", "price": 20.00, "weight": "Sport", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "sport", "purple"], "color": "Sabiduria", "description": purple+wool+sport, "image": "/images/yarn/purple.avif"},
    {"id": 14, "manufacturer": "Malabrigo", "model": "Arroyo", "price": 20.00, "weight": "Sport", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "sport", "blue"], "color": "Azul Profundo", "description": blue+wool+sport, "image": "/images/yarn/blue.avif"},
    {"id": 15, "manufacturer": "Malabrigo", "model": "Arroyo", "price": 20.00, "weight": "Sport", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "sport", "green"], "color": "Fiona", "description": green+wool+sport, "image": "/images/yarn/green.avif"},
    {"id": 16, "manufacturer": "Malabrigo", "model": "Arroyo", "price": 20.00, "weight": "Sport", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "sport", "yellow"], "color": "Frank Ochre", "description": yellow+wool+sport, "image": "/images/yarn/yellow.avif"},
    {"id": 17, "manufacturer": "Malabrigo", "model": "Arroyo", "price": 20.00, "weight": "Sport", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "sport", "orange"], "color": "Sunset", "description": orange+wool+sport, "image": "/images/yarn/orange.avif"},
    {"id": 18, "manufacturer": "Malabrigo", "model": "Arroyo", "price": 20.00, "weight": "Sport", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "sport", "red"], "color": "Ravelry Red", "description": red+wool+sport, "image": "/images/yarn/red.avif"},
    {"id": 19, "manufacturer": "Malabrigo", "model": "Arroyo", "price": 20.00, "weight": "Sport", "fiber": "100% Superwash Merino Wool", "tags": ["yarn", "wool", "sport", "white"], "color": "Whole Grain", "description": white+wool+sport, "image": "/images/yarn/white.avif"},
    
    {"id": 21, "manufacturer": "Malabrigo", "model": "Dos Tierras", "price": 20.00, "weight": "DK", "fiber": "50% Merino Wool, 50% Baby Alpaca", "tags": ["yarn", "wool", "alpaca", "dk", "black"], "color": "Black", "description": black+wool+dk, "image": "/images/yarn/black.avif"},
    {"id": 22, "manufacturer": "Malabrigo", "model": "Dos Tierras", "price": 20.00, "weight": "DK", "fiber": "50% Merino Wool, 50% Baby Alpaca", "tags": ["yarn", "wool", "alpaca", "dk", "gray"], "color": "Gris", "description": gray+wool+dk, "image": "/images/yarn/gray.avif"},
    {"id": 23, "manufacturer": "Malabrigo", "model": "Dos Tierras", "price": 20.00, "weight": "DK", "fiber": "50% Merino Wool, 50% Baby Alpaca", "tags": ["yarn", "wool", "alpaca", "dk", "purple"], "color": "Sabiduria", "description": purple+wool+dk, "image": "/images/yarn/purple.avif"},
    {"id": 24, "manufacturer": "Malabrigo", "model": "Dos Tierras", "price": 20.00, "weight": "DK", "fiber": "50% Merino Wool, 50% Baby Alpaca", "tags": ["yarn", "wool", "alpaca", "dk", "blue"], "color": "Azul Profundo", "description": blue+wool+dk, "image": "/images/yarn/blue.avif"},
    {"id": 25, "manufacturer": "Malabrigo", "model": "Dos Tierras", "price": 20.00, "weight": "DK", "fiber": "50% Merino Wool, 50% Baby Alpaca", "tags": ["yarn", "wool", "alpaca", "dk", "green"], "color": "Fiona", "description": green+wool+dk, "image": "/images/yarn/green.avif"},
    {"id": 26, "manufacturer": "Malabrigo", "model": "Dos Tierras", "price": 20.00, "weight": "DK", "fiber": "50% Merino Wool, 50% Baby Alpaca", "tags": ["yarn", "wool", "alpaca", "dk", "yellow"], "color": "Frank Ochre", "description": yellow+wool+dk, "image": "/images/yarn/yellow.avif"},
    {"id": 27, "manufacturer": "Malabrigo", "model": "Dos Tierras", "price": 20.00, "weight": "DK", "fiber": "50% Merino Wool, 50% Baby Alpaca", "tags": ["yarn", "wool", "alpaca", "dk", "orange"], "color": "Sunset", "description": orange+wool+dk, "image": "/images/yarn/orange.avif"},
    {"id": 28, "manufacturer": "Malabrigo", "model": "Dos Tierras", "price": 20.00, "weight": "DK", "fiber": "50% Merino Wool, 50% Baby Alpaca", "tags": ["yarn", "wool", "alpaca", "dk", "red"], "color": "Ravelry Red", "description": red+wool+dk, "image": "/images/yarn/red.avif"},
    {"id": 29, "manufacturer": "Malabrigo", "model": "Dos Tierras", "price": 20.00, "weight": "DK", "fiber": "50% Merino Wool, 50% Baby Alpaca", "tags": ["yarn", "wool", "alpaca", "dk", "white"], "color": "Whole Grain", "description": white+wool+dk, "image": "/images/yarn/white.avif"},
    
    {"id": 31, "manufacturer": "Malabrigo", "model": "Worsted", "price": 20.00, "weight": "Worsted", "fiber": "100% Merino Wool", "tags": ["yarn", "wool", "worsted", "black"], "color": "Black", "description": black+wool+worsted, "image": "/images/yarn/black.avif"},
    {"id": 32, "manufacturer": "Malabrigo", "model": "Worsted", "price": 20.00, "weight": "Worsted", "fiber": "100% Merino Wool", "tags": ["yarn", "wool", "worsted", "gray"], "color": "Gris", "description": gray+wool+worsted, "image": "/images/yarn/gray.avif"},
    {"id": 33, "manufacturer": "Malabrigo", "model": "Worsted", "price": 20.00, "weight": "Worsted", "fiber": "100% Merino Wool", "tags": ["yarn", "wool", "worsted", "purple"], "color": "Sabiduria", "description": purple+wool+worsted, "image": "/images/yarn/purple.avif"},
    {"id": 34, "manufacturer": "Malabrigo", "model": "Worsted", "price": 20.00, "weight": "Worsted", "fiber": "100% Merino Wool", "tags": ["yarn", "wool", "worsted", "blue"], "color": "Azul Profundo", "description": blue+wool+worsted, "image": "/images/yarn/blue.avif"},
    {"id": 35, "manufacturer": "Malabrigo", "model": "Worsted", "price": 20.00, "weight": "Worsted", "fiber": "100% Merino Wool", "tags": ["yarn", "wool", "worsted", "green"], "color": "Fiona", "description": green+wool+worsted, "image": "/images/yarn/green.avif"},
    {"id": 36, "manufacturer": "Malabrigo", "model": "Worsted", "price": 20.00, "weight": "Worsted", "fiber": "100% Merino Wool", "tags": ["yarn", "wool", "worsted", "yellow"], "color": "Frank Ochre", "description": yellow+wool+worsted, "image": "/images/yarn/yellow.avif"},
    {"id": 37, "manufacturer": "Malabrigo", "model": "Worsted", "price": 20.00, "weight": "Worsted", "fiber": "100% Merino Wool", "tags": ["yarn", "wool", "worsted", "orange"], "color": "Sunset", "description": orange+wool+worsted, "image": "/images/yarn/orange.avif"},
    {"id": 38, "manufacturer": "Malabrigo", "model": "Worsted", "price": 20.00, "weight": "Worsted", "fiber": "100% Merino Wool", "tags": ["yarn", "wool", "worsted", "red"], "color": "Ravelry Red", "description": red+wool+worsted, "image": "/images/yarn/red.avif"},
    {"id": 39, "manufacturer": "Malabrigo", "model": "Worsted", "price": 20.00, "weight": "Worsted", "fiber": "100% Merino Wool", "tags": ["yarn", "wool", "worsted", "white"], "color": "Whole Grain", "description": white+wool+worsted, "image": "/images/yarn/white.avif"},

    {"id": 41, "manufacturer": "Vellera", "model": "Vernal", "price": 15.00, "weight": "Fingering", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "fingering", "black"], "color": "Black", "description": black+cotton+fingering, "image": "/images/yarn/black.avif"},
    {"id": 42, "manufacturer": "Vellera", "model": "Vernal", "price": 15.00, "weight": "Fingering", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "fingering", "gray"], "color": "Gris", "description": gray+cotton+fingering, "image": "/images/yarn/gray.avif"},
    {"id": 43, "manufacturer": "Vellera", "model": "Vernal", "price": 15.00, "weight": "Fingering", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "fingering", "purple"], "color": "Sabiduria", "description": purple+cotton+fingering, "image": "/images/yarn/purple.avif"},
    {"id": 44, "manufacturer": "Vellera", "model": "Vernal", "price": 15.00, "weight": "Fingering", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "fingering", "blue"], "color": "Azul Profundo", "description": blue+cotton+fingering, "image": "/images/yarn/blue.avif"},
    {"id": 45, "manufacturer": "Vellera", "model": "Vernal", "price": 15.00, "weight": "Fingering", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "fingering", "green"], "color": "Fiona", "description": green+cotton+fingering, "image": "/images/yarn/green.avif"},
    {"id": 46, "manufacturer": "Vellera", "model": "Vernal", "price": 15.00, "weight": "Fingering", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "fingering", "yellow"], "color": "Frank Ochre", "description": yellow+cotton+fingering, "image": "/images/yarn/yellow.avif"},
    {"id": 47, "manufacturer": "Vellera", "model": "Vernal", "price": 15.00, "weight": "Fingering", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "fingering", "orange"], "color": "Sunset", "description": orange+cotton+fingering, "image": "/images/yarn/orange.avif"},
    {"id": 48, "manufacturer": "Vellera", "model": "Vernal", "price": 15.00, "weight": "Fingering", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "fingering", "red"], "color": "Ravelry Red", "description": red+cotton+fingering, "image": "/images/yarn/red.avif"},
    {"id": 49, "manufacturer": "Vellera", "model": "Vernal", "price": 15.00, "weight": "Fingering", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "fingering", "white"], "color": "Whole Grain", "description": white+cotton+fingering, "image": "/images/yarn/white.avif"},
    
    {"id": 51, "manufacturer": "Vellera", "model": "Solstice", "price": 15.00, "weight": "Sport", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "sport", "black"], "color": "Black", "description": black+cotton+sport, "image": "/images/yarn/black.avif"},
    {"id": 52, "manufacturer": "Vellera", "model": "Solstice", "price": 15.00, "weight": "Sport", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "sport", "gray"], "color": "Gris", "description": gray+cotton+sport, "image": "/images/yarn/gray.avif"},
    {"id": 53, "manufacturer": "Vellera", "model": "Solstice", "price": 15.00, "weight": "Sport", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "sport", "purple"], "color": "Sabiduria", "description": purple+cotton+sport, "image": "/images/yarn/purple.avif"},
    {"id": 54, "manufacturer": "Vellera", "model": "Solstice", "price": 15.00, "weight": "Sport", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "sport", "blue"], "color": "Azul Profundo", "description": blue+cotton+sport, "image": "/images/yarn/blue.avif"},
    {"id": 55, "manufacturer": "Vellera", "model": "Solstice", "price": 15.00, "weight": "Sport", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "sport", "green"], "color": "Fiona", "description": green+cotton+sport, "image": "/images/yarn/green.avif"},
    {"id": 56, "manufacturer": "Vellera", "model": "Solstice", "price": 15.00, "weight": "Sport", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "sport", "yellow"], "color": "Frank Ochre", "description": yellow+cotton+sport, "image": "/images/yarn/yellow.avif"},
    {"id": 57, "manufacturer": "Vellera", "model": "Solstice", "price": 15.00, "weight": "Sport", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "sport", "orange"], "color": "Sunset", "description": orange+cotton+sport, "image": "/images/yarn/orange.avif"},
    {"id": 58, "manufacturer": "Vellera", "model": "Solstice", "price": 15.00, "weight": "Sport", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "sport", "red"], "color": "Ravelry Red", "description": red+cotton+sport, "image": "/images/yarn/red.avif"},
    {"id": 59, "manufacturer": "Vellera", "model": "Solstice", "price": 15.00, "weight": "Sport", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "sport", "white"], "color": "Whole Grain", "description": white+cotton+sport, "image": "/images/yarn/white.avif"},
    
    {"id": 61, "manufacturer": "Vellera", "model": "Equinox", "price": 15.00, "weight": "DK", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "dk", "black"], "color": "Black", "description": black+cotton+dk, "image": "/images/yarn/black.avif"},
    {"id": 62, "manufacturer": "Vellera", "model": "Equinox", "price": 15.00, "weight": "DK", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "dk", "gray"], "color": "Gris", "description": gray+cotton+dk, "image": "/images/yarn/gray.avif"},
    {"id": 63, "manufacturer": "Vellera", "model": "Equinox", "price": 15.00, "weight": "DK", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "dk", "purple"], "color": "Sabiduria", "description": purple+cotton+dk, "image": "/images/yarn/purple.avif"},
    {"id": 64, "manufacturer": "Vellera", "model": "Equinox", "price": 15.00, "weight": "DK", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "dk", "blue"], "color": "Azul Profundo", "description": blue+cotton+dk, "image": "/images/yarn/blue.avif"},
    {"id": 65, "manufacturer": "Vellera", "model": "Equinox", "price": 15.00, "weight": "DK", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "dk", "green"], "color": "Fiona", "description": green+cotton+dk, "image": "/images/yarn/green.avif"},
    {"id": 66, "manufacturer": "Vellera", "model": "Equinox", "price": 15.00, "weight": "DK", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "dk", "yellow"], "color": "Frank Ochre", "description": yellow+cotton+dk, "image": "/images/yarn/yellow.avif"},
    {"id": 67, "manufacturer": "Vellera", "model": "Equinox", "price": 15.00, "weight": "DK", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "dk", "orange"], "color": "Sunset", "description": orange+cotton+dk, "image": "/images/yarn/orange.avif"},
    {"id": 68, "manufacturer": "Vellera", "model": "Equinox", "price": 15.00, "weight": "DK", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "dk", "red"], "color": "Ravelry Red", "description": red+cotton+dk, "image": "/images/yarn/red.avif"},
    {"id": 69, "manufacturer": "Vellera", "model": "Equinox", "price": 15.00, "weight": "DK", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "dk", "white"], "color": "Whole Grain", "description": white+cotton+dk, "image": "/images/yarn/white.avif"},
    
    {"id": 71, "manufacturer": "Vellera", "model": "Hibernal", "price": 15.00, "weight": "Worsted", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "worsted", "black"], "color": "Black", "description": black+cotton+worsted, "image": "/images/yarn/black.avif"},
    {"id": 72, "manufacturer": "Vellera", "model": "Hibernal", "price": 15.00, "weight": "Worsted", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "worsted", "gray"], "color": "Gris", "description": gray+cotton+worsted, "image": "/images/yarn/gray.avif"},
    {"id": 73, "manufacturer": "Vellera", "model": "Hibernal", "price": 15.00, "weight": "Worsted", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "worsted", "purple"], "color": "Sabiduria", "description": purple+cotton+worsted, "image": "/images/yarn/purple.avif"},
    {"id": 74, "manufacturer": "Vellera", "model": "Hibernal", "price": 15.00, "weight": "Worsted", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "worsted", "blue"], "color": "Azul Profundo", "description": blue+cotton+worsted, "image": "/images/yarn/blue.avif"},
    {"id": 75, "manufacturer": "Vellera", "model": "Hibernal", "price": 15.00, "weight": "Worsted", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "worsted", "green"], "color": "Fiona", "description": green+cotton+worsted, "image": "/images/yarn/green.avif"},
    {"id": 76, "manufacturer": "Vellera", "model": "Hibernal", "price": 15.00, "weight": "Worsted", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "worsted", "yellow"], "color": "Frank Ochre", "description": yellow+cotton+worsted, "image": "/images/yarn/yellow.avif"},
    {"id": 77, "manufacturer": "Vellera", "model": "Hibernal", "price": 15.00, "weight": "Worsted", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "worsted", "orange"], "color": "Sunset", "description": orange+cotton+worsted, "image": "/images/yarn/orange.avif"},
    {"id": 78, "manufacturer": "Vellera", "model": "Hibernal", "price": 15.00, "weight": "Worsted", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "worsted", "red"], "color": "Ravelry Red", "description": red+cotton+worsted, "image": "/images/yarn/red.avif"},
    {"id": 79, "manufacturer": "Vellera", "model": "Hibernal", "price": 15.00, "weight": "Worsted", "fiber": "100% Pima Cotton", "tags": ["yarn", "cotton", "worsted", "white"], "color": "Whole Grain", "description": white+cotton+worsted, "image": "/images/yarn/white.avif"},
    
    {"id": 81, "manufacturer": "Iteris", "model": "Embrace", "price": 22.00, "weight": "Fingering", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "fingering", "black"], "color": "Black", "description": black+alpaca+fingering, "image": "/images/yarn/black.avif"},
    {"id": 82, "manufacturer": "Iteris", "model": "Embrace", "price": 22.00, "weight": "Fingering", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "fingering", "gray"], "color": "Gris", "description": gray+alpaca+fingering, "image": "/images/yarn/gray.avif"},
    {"id": 83, "manufacturer": "Iteris", "model": "Embrace", "price": 22.00, "weight": "Fingering", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "fingering", "purple"], "color": "Sabiduria", "description": purple+alpaca+fingering, "image": "/images/yarn/purple.avif"},
    {"id": 84, "manufacturer": "Iteris", "model": "Embrace", "price": 22.00, "weight": "Fingering", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "fingering", "blue"], "color": "Azul Profundo", "description": blue+alpaca+fingering, "image": "/images/yarn/blue.avif"},
    {"id": 85, "manufacturer": "Iteris", "model": "Embrace", "price": 22.00, "weight": "Fingering", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "fingering", "green"], "color": "Fiona", "description": green+alpaca+fingering, "image": "/images/yarn/green.avif"},
    {"id": 86, "manufacturer": "Iteris", "model": "Embrace", "price": 22.00, "weight": "Fingering", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "fingering", "yellow"], "color": "Frank Ochre", "description": yellow+alpaca+fingering, "image": "/images/yarn/yellow.avif"},
    {"id": 87, "manufacturer": "Iteris", "model": "Embrace", "price": 22.00, "weight": "Fingering", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "fingering", "orange"], "color": "Sunset", "description": orange+alpaca+fingering, "image": "/images/yarn/orange.avif"},
    {"id": 88, "manufacturer": "Iteris", "model": "Embrace", "price": 22.00, "weight": "Fingering", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "fingering", "red"], "color": "Ravelry Red", "description": red+alpaca+fingering, "image": "/images/yarn/red.avif"},
    {"id": 89, "manufacturer": "Iteris", "model": "Embrace", "price": 22.00, "weight": "Fingering", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "fingering", "white"], "color": "Whole Grain", "description": white+alpaca+fingering, "image": "/images/yarn/white.avif"},
    
    {"id": 91, "manufacturer": "Iteris", "model": "Cuddle", "price": 22.00, "weight": "Sport", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "sport", "black"], "color": "Black", "description": black+alpaca+sport, "image": "/images/yarn/black.avif"},
    {"id": 92, "manufacturer": "Iteris", "model": "Cuddle", "price": 22.00, "weight": "Sport", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "sport", "gray"], "color": "Gris", "description": gray+alpaca+sport, "image": "/images/yarn/gray.avif"},
    {"id": 93, "manufacturer": "Iteris", "model": "Cuddle", "price": 22.00, "weight": "Sport", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "sport", "purple"], "color": "Sabiduria", "description": purple+alpaca+sport, "image": "/images/yarn/purple.avif"},
    {"id": 94, "manufacturer": "Iteris", "model": "Cuddle", "price": 22.00, "weight": "Sport", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "sport", "blue"], "color": "Azul Profundo", "description": blue+alpaca+sport, "image": "/images/yarn/blue.avif"},
    {"id": 95, "manufacturer": "Iteris", "model": "Cuddle", "price": 22.00, "weight": "Sport", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "sport", "green"], "color": "Fiona", "description": green+alpaca+sport, "image": "/images/yarn/green.avif"},
    {"id": 96, "manufacturer": "Iteris", "model": "Cuddle", "price": 22.00, "weight": "Sport", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "sport", "yellow"], "color": "Frank Ochre", "description": yellow+alpaca+sport, "image": "/images/yarn/yellow.avif"},
    {"id": 97, "manufacturer": "Iteris", "model": "Cuddle", "price": 22.00, "weight": "Sport", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "sport", "orange"], "color": "Sunset", "description": orange+alpaca+sport, "image": "/images/yarn/orange.avif"},
    {"id": 98, "manufacturer": "Iteris", "model": "Cuddle", "price": 22.00, "weight": "Sport", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "sport", "red"], "color": "Ravelry Red", "description": red+alpaca+sport, "image": "/images/yarn/red.avif"},
    {"id": 99, "manufacturer": "Iteris", "model": "Cuddle", "price": 22.00, "weight": "Sport", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "sport", "white"], "color": "Whole Grain", "description": white+alpaca+sport, "image": "/images/yarn/white.avif"},
    
    {"id": 101, "manufacturer": "Iteris", "model": "Hug", "price": 22.00, "weight": "DK", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "dk", "black"], "color": "Black", "description": black+alpaca+dk, "image": "/images/yarn/black.avif"},
    {"id": 102, "manufacturer": "Iteris", "model": "Hug", "price": 22.00, "weight": "DK", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "dk", "gray"], "color": "Gris", "description": gray+alpaca+dk, "image": "/images/yarn/gray.avif"},
    {"id": 103, "manufacturer": "Iteris", "model": "Hug", "price": 22.00, "weight": "DK", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "dk", "purple"], "color": "Sabiduria", "description": purple+alpaca+dk, "image": "/images/yarn/purple.avif"},
    {"id": 104, "manufacturer": "Iteris", "model": "Hug", "price": 22.00, "weight": "DK", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "dk", "blue"], "color": "Azul Profundo", "description": blue+alpaca+dk, "image": "/images/yarn/blue.avif"},
    {"id": 105, "manufacturer": "Iteris", "model": "Hug", "price": 22.00, "weight": "DK", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "dk", "green"], "color": "Fiona", "description": green+alpaca+dk, "image": "/images/yarn/green.avif"},
    {"id": 106, "manufacturer": "Iteris", "model": "Hug", "price": 22.00, "weight": "DK", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "dk", "yellow"], "color": "Frank Ochre", "description": yellow+alpaca+dk, "image": "/images/yarn/yellow.avif"},
    {"id": 107, "manufacturer": "Iteris", "model": "Hug", "price": 22.00, "weight": "DK", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "dk", "orange"], "color": "Sunset", "description": orange+alpaca+dk, "image": "/images/yarn/orange.avif"},
    {"id": 108, "manufacturer": "Iteris", "model": "Hug", "price": 22.00, "weight": "DK", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "dk", "red"], "color": "Ravelry Red", "description": red+alpaca+dk, "image": "/images/yarn/red.avif"},
    {"id": 109, "manufacturer": "Iteris", "model": "Hug", "price": 22.00, "weight": "DK", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "dk", "white"], "color": "Whole Grain", "description": white+alpaca+dk, "image": "/images/yarn/white.avif"},
    
    {"id": 111, "manufacturer": "Iteris", "model": "Snuggle", "price": 22.00, "weight": "Worsted", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "worsted", "black"], "color": "Black", "description": black+alpaca+worsted, "image": "/images/yarn/black.avif"},
    {"id": 112, "manufacturer": "Iteris", "model": "Snuggle", "price": 22.00, "weight": "Worsted", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "worsted", "gray"], "color": "Gris", "description": gray+alpaca+worsted, "image": "/images/yarn/gray.avif"},
    {"id": 113, "manufacturer": "Iteris", "model": "Snuggle", "price": 22.00, "weight": "Worsted", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "worsted", "purple"], "color": "Sabiduria", "description": purple+alpaca+worsted, "image": "/images/yarn/purple.avif"},
    {"id": 114, "manufacturer": "Iteris", "model": "Snuggle", "price": 22.00, "weight": "Worsted", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "worsted", "blue"], "color": "Azul Profundo", "description": blue+alpaca+worsted, "image": "/images/yarn/blue.avif"},
    {"id": 115, "manufacturer": "Iteris", "model": "Snuggle", "price": 22.00, "weight": "Worsted", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "worsted", "green"], "color": "Fiona", "description": green+alpaca+worsted, "image": "/images/yarn/green.avif"},
    {"id": 116, "manufacturer": "Iteris", "model": "Snuggle", "price": 22.00, "weight": "Worsted", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "worsted", "yellow"], "color": "Frank Ochre", "description": yellow+alpaca+worsted, "image": "/images/yarn/yellow.avif"},
    {"id": 117, "manufacturer": "Iteris", "model": "Snuggle", "price": 22.00, "weight": "Worsted", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "worsted", "orange"], "color": "Sunset", "description": orange+alpaca+worsted, "image": "/images/yarn/orange.avif"},
    {"id": 118, "manufacturer": "Iteris", "model": "Snuggle", "price": 22.00, "weight": "Worsted", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "worsted", "red"], "color": "Ravelry Red", "description": red+alpaca+worsted, "image": "/images/yarn/red.avif"},
    {"id": 119, "manufacturer": "Iteris", "model": "Snuggle", "price": 22.00, "weight": "Worsted", "fiber": "100% Baby Alpaca", "tags": ["yarn", "alpaca", "worsted", "white"], "color": "Whole Grain", "description": white+alpaca+worsted, "image": "/images/yarn/white.avif"},
]

export default products;